2016/08/11 15:11:30 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
' in C:\test_zadanie\yii-1.1.17.467ff50\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\test_zadanie\yii-1.1.17.467ff50\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\test_zadanie\yii-1.1.17.467ff50\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\test_zadanie\yii-1.1.17.467ff50\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\test_zadanie\yii-1.1.17.467ff50\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\test_zadanie\protected\models\Gruppa.php(8): CModule->__get('db')
#5 C:\test_zadanie\protected\controllers\MainController.php(18): Gruppa->getAll()
#6 C:\test_zadanie\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): MainController->actionIndex()
#7 C:\test_zadanie\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\test_zadanie\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\test_zadanie\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\test_zadanie\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('')
#11 C:\test_zadanie\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#12 C:\test_zadanie\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\test_zadanie\public\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/
---
